# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hNmbZyXWQb1fzCp-v__hjAMhiLzYZlQ

# **What is NumPy?**

NumPy (Numerical Python) is a powerful Python library used for numerical computing, especially when working with arrays, matrices, and mathematical operations.

**Why NumPy is Important?**

Before NumPy:

* Python lists are slow
* Hard to do complex math
* No support for multi-dimensional data

With NumPy:

* ⚡ Very fast (written in C internally)
* 📊 Supports multi-dimensional arrays
* 🧮 Built-in mathematical functions
* 🤖 Used in ML, AI, Data Science

**Core Concept: ndarray (N-Dimensional Array)**

The heart of NumPy is:

> ndarray = N-dimensional array

Think of it like:

1D → list

2D → table (rows × columns)

3D → cube (used in images, ML)

**Creating Arrays**

1. From Python List
"""

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

"""2. Multi-dimensional Array"""

import numpy as np

arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

"""3. Special Arrays"""

import numpy as np

np.zeros((2,3))   # all zeros
np.ones((2,2))    # all ones
np.eye(3)         # identity matrix
np.arange(0,10,2) # range
np.linspace(0,1,5)# equal intervals

"""**Array Properties**"""

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)   # (rows, columns)
print(arr.ndim)    # number of dimensions
print(arr.size)    # total elements
print(arr.dtype)   # data type

"""**Why NumPy is Fast ?**

👉NumPy uses vectorization

Instead of loop:


```
# Python way (slow)
result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])
```
Numpy ways:


```
result = arr1 + arr2
```

* ✔ No loops
* ✔ Faster execution
* ✔ Cleaner code


---

**Operations on Arrays**
"""

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a ** 2) # [1 4 9]

"""**Mathematical Functions**"""

import numpy as np

a = 5
np.sqrt(a)
np.exp(a)
np.mean(a)
np.std(a)
np.sum(a)
np.max(a)
np.min(a)

"""**Indexing & Slicing**"""

import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[0])      # 10
print(arr[1:4])    # [20 30 40]

"""2D Indexing



```
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr2[0,1])   # 2
print(arr2[:,1])   # column
```

**🔄 Reshaping Arrays**
"""

import numpy as np

arr = np.arange(6)
print(arr.reshape(2,3))

"""**Broadcasting**

👉 Allows operations between different shapes

* Automatically expands values
* Very powerful in ML
"""

import numpy as np

a = np.array([1,2,3])
b = 2

print(a + b)  # [3 4 5]

"""**NumPy vs Python List**


| Feature         | Python List  |  NumPy Array |
| --------------- | -----------  |  ----------- |
| Speed           | Slow         |  Fast        |
| Memory          | High         |  Low         |
| Math Ops        | Limited      |  Powerful    |
| Multi-Dimension | No           |  Yes         |

# **Random Numbers in NumPy**

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.
"""

#Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)
print(x)

"""**Random Data Distribution**

**Random Distribution** -
A random distribution is a set of random numbers that follow a certain probability density function.

> The sum of all probability numbers should be 1.
"""

from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

"""**Binomial Distribution**

Binomial Distribution is a Discrete Distribution.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

It has three parameters:

* n - number of trials.

* p - probability of occurrence of each trial

* size - The shape of the returned array.
"""

from numpy import random

x = random.binomial(n=10, p=0.5, size=10)
print(x)

"""*Visualization of Binomial Distribution*"""

from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.displot(random.binomial(n=10, p=0.5, size=1000))

plt.show()

"""**Logistic Distribution**

Logistic Distribution is used to describe growth.

Used extensively in machine learning in logistic regression, neural networks etc.

It has three parameters:

* loc - mean, where the peak is. Default 0.

* scale - standard deviation, the flatness of distribution. Default 1.

* size - The shape of the returned array.
"""

from numpy import random

x = random.logistic(loc=1, scale=2, size=(2, 3))
print(x)

"""*Visualization of Logistic Distribution*"""

from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.displot(random.logistic(size=1000), kind="kde")

plt.show()

"""**Exponential Distribution**

Exponential distribution is used for describing time till next event e.g. failure/success etc.

It has two parameters:

* scale - inverse of rate ( see lam in poisson distribution ) defaults to 1.0.

* size - The shape of the returned array.
"""

#Draw out a sample for exponential distribution with 2.0 scale with 2x3 size:

from numpy import random

x = random.exponential(scale=2, size=(2, 3))
print(x)

"""*Visualization of Exponential Distribution*"""

from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.displot(random.exponential(size=1000), kind="kde")

plt.show()